# Generated by `ryra org machines install`. Do not edit: the next install
# overwrites this file.
#
# Empty here, and it has to be. A template that carried a key would be a
# template that let its author into every machine started from it, which is the
# same argument `access.nix` makes for shipping root's key list empty.
#
# It exists anyway, rather than being created on first install, so that the
# flake imports a file that is always there: a module list naming something
# absent does not evaluate, and "install writes it" would mean the template does
# not build until it has been installed once.
{ ... }:
{
  users.users.root.openssh.authorizedKeys.keys = [ ];
}
